### ISSUE TITLE
Erratic Tax calculation 

### ISSUE THREAD

**Issue by Mediabahn** [wojodesign/simplecart-js#142] opened 2011-09-05 01:59 UTC
After testing for an hour...

Some product have tax calculated in paypal other don't ? ;-((

tax ok

a href="javascript:;" onclick="simpleCart.add('name=ÉCOUTE ACTIVE', 'price=40.00','date=07/11/2011','quantity=1');" >Ajouter au panier</a

tax not calculated

a href="javascript:;" onclick="simpleCart.add('name=PARLER EN PUBLIC', 'price=50.00','date=15/10/2011','quantity=1');" >Ajouter au panier</a

head section:

simpleCart.currency = CAD;
simpleCart.taxRate = 0.13925;
simpleCart.checkoutTo = PayPal;

simpleCart.cartHeaders = [ "Name" , "date", "Quantity", "Price" ,  "Total" ];

Any idea ?

TIA

**Comment by xelaxam** [comment] 2011-09-14 01:30
I'm having the same problem as you and even worst... I don't get any tax.I'm in quebec too ( think your are in quebec, the car currency and the tps and tvq get a 13,925 tax rate). I tried different tax rate, different currency. I started over but nothing happen...

Anyone has idea?

**Comment by xelaxam** [comment] 2011-09-14 15:30
I made some test 
First, I don't know why but my paypal don't take tax with more than 2 decimal, on my side. The problem is when i put a tax rate of 0.1393 i get 13,920000002% which scew up paypal. Also if i add item for less than 1$ no tax are applied on them.

**Comment by Mediabahn** [comment] 2011-09-14 19:41
Allo Xelaxam !

Also bug with tax, i thought about puting price with include tax, not very elegant...
I wander if Paypal can calculated tax for us, new to paypal...
i will look at this, during the week ! 
Contact me clavoie À technologiebahn.com

A+

**Comment by brettwejrowski** [comment] 2011-11-14 05:11
Hmmm I'm not sure if this is an error with simpleCart(js) or PayPal.  I think it might be fixed by adding .toFixed() to the tax input when checking out to paypal.

**Comment by Mediabahn** [comment] 2011-11-14 14:55
Thank you brettwejrowski,

Bypass the problem i let Paypal calculate the tax !

**Comment by ragtech** [comment] 2011-11-16 22:20
MASTER (me.Version = '2.2.2';)

can't get taxes to work at all with PayPal Checkout... anyone noticed this? Is there a FIX? 

brettwejrowski commented above to add .toFixed() to the tax input --- Where exactly should this be added? I would like to try...

**Comment by ragtech** [comment] 2011-11-16 22:23
Whoops... just tried again and it worked this time; I guess ''Erratic'' Tax calculation would be accurate then...

**Comment by bajabaq** [comment] 2012-01-03 05:01
like ragtech, I can't get taxes to work with PayPal checkout - I specified 
simpleCart.taxRate = 0.05; in the header - the same place as the simpleCart.checkoutTo = PayPal; etc.

The proper tax shows up in the cart and in the final total, but it fails to be transmitted to Paypal. I tried the .toFix() solution.

Do I have to set something on the paypal side to get this to work? I noticed that ragtech's sample: http://uswebsitecreation.com/tax_example/tax_example.html
seems to work fine.

**Comment by bajabaq** [comment] 2012-01-08 19:25
Ok, I solved my issue. As mentioned above by brettwejrowski, adding the .toFixed() did it (Was a value with 17 digites after the decimal)

The place to do this is around line 275 in the paypalCheckout function, the line should go from:

form.appendChild(me.createHiddenElement("tax_cart",me.taxCost ));

to this:

form.appendChild(me.createHiddenElement("tax_cart",me.taxCost.toFixed(2) ));

Nothing needs to be modified on the paypal side of things

**Comment by brettwejrowski** [comment] 2012-02-15 20:31
fixed with pull request from plainlystated

**Closed as completed by brettwejrowski** 2012-02-15 20:31 UTC
Labels: Bug
